- name: Install nvm dependencies
  apt:
    name: [ 'build-essential', 'libssl-dev' ]
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: nvm

- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ wsl_bootstrap_user_home }}/.nvm"
  tags: nvm

- name: Source nvm in ~/.zshrc
  lineinfile:
    path: "{{ wsl_bootstrap_user_home }}/.zshrc"
    line: "{{ item }}"
  with_items:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
  tags: nvm
