---
- name: Collecting Facts
  hosts: local
  gather_facts: yes
  tasks:
    - name: Prompt for full name
      pause:
        prompt: "Your full name (will be used in git commit messages)"
      register: full_name_input
      when: not full_name

    - name: Set full name as fact
      set_fact:
        full_name: "{{ full_name_input.user_input }}"
      when: not full_name

    - name: Prompt for git email
      pause:
        prompt: "Your email to sign git commits"
      when: not git_email
      register: git_email_input

    - name: Set git email as fact
      set_fact:
        git_email: "{{ git_email_input.user_input }}"
      when: not git_email

- name: Set up local development environment
  hosts: local
  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - common
    - git
    - wsl
    - zsh
    - fzf
    - thefuck
    - ssh
    - docker
    - nvm
    - earthly
