# Installation and setup
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
# - import_tasks: redhat.yml
#   when: ansible_os_family == "RedHat"
# - import_tasks: osx.yml
#   when: ansible_os_family == "Darwin"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh"
  register: cloning

- name: Copying our .zshrc to ~/.zshrc
  copy:
    src: "{{ dotfiles_home }}/roles/zsh/files/.zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
  when: cloning is succeeded

# When using WSL on Windows prior 16215 build, we can't change the shell with
# the `chsh -s /usr/bin/zsh` command. We need to launch zsh from the .bashrc file.
- name: Launch zsh from the .bashrc file
  lineinfile:
    path: "{{ dotfiles_user_home }}/.bashrc"
    regexp: 'exec zsh'
    line: "if [ -t 1 ]; then exec zsh; fi"