
# Pip is installed in common role
# - name: Install Python dependencies for docker compose
#   easy_install:
#     name: pip
#     state: latest
#   become: yes

- name: Install docker compose
  pip:
    name: docker-compose
    state: latest
  become: yes