
- name: Install ruby
  # apt: "name={{ item }} state=present"
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
  with_items:
    - ruby
    - ruby-dev
  become: yes

# - name: Install docker-sync
#   gem:
#     name: docker-sync
#     state: latest
#   become: yes

# For unknown reasons the gem module tasks does not intall docker-sync properly
# But the command module task does it well:
- name: Install docker-sync
  command: gem install docker-sync
  become: yes

- name: Install Unison
  action: "{{ ansible_pkg_mgr }} pkg=unison state=present"
  become: yes
  # apt: "name=unison state=present"


# - name: Download Unison
#   get_url:
#     url: https://github.com/bcpierce00/unison/archive/2.48.4.tar.gz
#     dest: /tmp/2.48.4.tar.gz
#   register: unison_download

# UNISON_VERSION=2.48.4
# sudo apt-get -y install inotify-tools ocaml-nox build-essential
# curl -L https://github.com/bcpierce00/unison/archive/${UNISON_VERSION}.tar.gz | tar zxv -C /tmp
# cd /tmp/unison-${UNISON_VERSION}
# sed -i -e 's/GLIBC_SUPPORT_INOTIFY 0/GLIBC_SUPPORT_INOTIFY 1/' src/fsmonitor/linux/inotify_stubs.c
# make UISTYLE=text NATIVE=true STATIC=true
# cp src/unison src/unison-fsmonitor /usr/local/bin


# - name: Install Unison build dependencies
#   apt: "name={{ item }} state=present"
#   with_items:
#     - ocaml-nox
#     - make
#     - emacs-nox
#   become: yes

# - name: Download Unison
#   get_url:
#     url: https://github.com/bcpierce00/unison/archive/2.48.4.tar.gz
#     dest: /tmp/2.48.4.tar.gz
#   register: unison_download

# - name: Unarchive Unison
#   unarchive:
#     src: /tmp/2.48.4.tar.gz
#     dest: /tmp
#   when: unison_download|succeeded

# - name: Make Unison
#   make:
#     chdir: /tmp/unison-2.48.4
#     target: install
#     params: UISTYLE=text
#   become: yes

# - name: Copy Unison bin files
#   command: |
#     cp /tmp/unison-2.48.4/unison /usr/local/bin/unison
#     cp /tmp/unison-2.48.4/unison-fsmonitor /usr/local/bin/unison-fsmonitor
#   become: yes