# Install the fuck tool: https://github.com/nvbn/thefuck

- name: Install pip pre-requisites
  apt: 
    name: [ "python3-dev", "python3-pip", "python3-setuptools" ]
    state: latest
    update_cache: yes
  become: yes

- name: Install the fuck for a user
  pip:
    name: thefuck
    extra_args: --user

- name: Edit ~/.zshrc to add fuck alias
  lineinfile:
    path: "{{ wsl_bootstrap_user_home }}/.zshrc"
    line: "{{ item }}"
  with_items:
    - 'eval $(thefuck --alias)'