# - name: Add nessessary PPAs
#   apt_repository:
#     repo: ppa:hadret/fswatch
#     state: present
#   become: yes

- name: Install common packages
  apt: 
    name: ['tree', 'python-pip', 'python-setuptools', 'ack']
    state: latest
    update_cache: yes
  become: yes
